# Generated by Django 5.2.4 on 2025-09-04 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_game_banner_url_game_trailer_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergamelist',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='usergamelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usergamelist',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usergamelist',
            name='status',
            field=models.CharField(choices=[('P', 'Para jogar'), ('J', 'Jogando'), ('C', 'Concluído'), ('A', 'Abandonado')], default='P', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='usergamelist',
            unique_together={('user', 'game')},
        ),
    ]
